pub mod d1_trebuchet;
pub mod d2_cube_conundrum;
pub mod d3_gear_ratios;
pub mod d4_scratchcards;
pub mod d5_fertilizer;
pub mod d6_wait_for_it;
pub mod d7_camel_cards;
pub mod d8_haunted_wasteland;
pub mod d9_mirage_maintenance;